export { default as useGetAuthorResponse } from './useGetAuthorResponsesQuery'
export { default as useGetRecipientResponse } from './useGetRecipientResponsesQuery'
export { default as useGetSingleAuthorResponse } from './useGetSingleAuthorResponse'
export { default as useGetSingleRecipientResponse } from './useGetSingleRecipientResponse'
export { default as useCloseSurvey } from './useCloseSurvey'
export { default as useDeleteSurvey } from './useDeleteSurvey'
